version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=SASL_PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=SASL_PLAINTEXT://kafka:9092
      - KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL=SASL_PLAINTEXT # 这里应该是协议，而非认证机制
      - KAFKA_INTER_BROKER_LISTENER_NAME=SASL_PLAINTEXT
      - KAFKA_SASL_ENABLED_MECHANISMS=GSSAPI
      - KAFKA_KERBEROS_PRINCIPAL=kafka/_HOST@YOUR.REALM.COM
      - KAFKA_KERBEROS_KEYTAB=/etc/kafka/kafka.service.keytab
      - KAFKA_OPTS=-Djava.security.auth.login.config=/etc/kafka/jaas.conf
      # 如果使用SSL，还需要配置相关的SSL参数
    volumes:
      - ./pzwj/krb5.conf:/etc/krb5.conf
      - ./pzwj/keytab:/etc/kafka/kafka.service.keytab
      - ./pzwj/jaas.conf:/etc/kafka/jaas.conf
    depends_on:
      - zookeeper